apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-simple
  name: backend-simple-deployment
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-simple
  template:
    metadata:
      labels:
        app: backend-simple
    spec:
      containers:
      - name: backend-simple
        image: scubagrant60/apitest-images:backend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-simple-service
  namespace: kong
  labels:
    app: backend-simple
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: backend-simple