apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-simple-deployment
  namespace: kong
  labels:
    app: frontend-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-simple
  template:
    metadata:
      labels:
        app: frontend-simple
    spec:
      containers:
      - name: frontend-simple
        image: scubagrant60/simpleapp:frontend_clean_nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kong
  name: frontend-simple-service
spec:
  type: ClusterIP  
  selector:
    app: frontend-simple
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP