apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapi
  name: testapi
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
        image: scubagrant60/apitest-images:backend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testapi
  namespace: kong
  labels:
    app: testapi
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: testapi